### ISSUE TITLE
Error on right-click dropdown menu

### ISSUE THREAD

**Issue by Ivaria** [Meorawr/LibDBCompartment#1]
Hi there, thank you for your helpful library.

The minimap icon data object I use works fine with LibDBIcon but that same data object used with LibDBCompartment produces the following error trying to display a dropdown menu on right-click:

```
3x SharedXML/UIDropDownMenu.lua:1133: Action[SetPoint] failed because[Cannot anchor to a region dependent on it]: attempted from: DropDownList1:SetPoint.
[string "=[C]"]: in function `SetPoint'
[string "@SharedXML/UIDropDownMenu.lua"]:1133: in function `ToggleDropDownMenu'
[string "@VuhDo/VuhDoAddonAdapter.lua"]:92: in function `OnClick'
[string "@VuhDo/Libs/LibDBCompartment/LibDBCompartment-1.0-3.lua"]:198: in function `OnDropDownButtonClick'
[string "@VuhDo/Libs/LibDBCompartment/LibDBCompartment-1.0-3.lua"]:67: in function `func'
[string "@SharedXML/UIDropDownMenu.lua"]:1007: in function `UIDropDownMenuButton_OnClick'
[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1: in function <[string "*UIDropDownMenuTemplates.xml:136_OnClick"]:1>

Locals:
(*temporary) = DropDownList1 {
 0 = <userdata>
 dropdown = Frame {
 }
 shouldRefresh = false
 numButtons = 1
 Border = DropDownList1Backdrop {
 }
 maxWidth = 50.833355
}
(*temporary) = "TOPLEFT"
(*temporary) = "DropDownList1Button1"
(*temporary) = "BOTTOMLEFT"
(*temporary) = 0
(*temporary) = -5
```

The data object specifics can be seen here: https://gitlab.vuhdo.io/vuhdo/vuhdo/-/blob/master/VuhDoAddonAdapter.lua#L87

Any thoughts on what could be the issue?

Thanks again!

**Comment by Meorawr** [comment]
That ToggleDropDownMenu call is basically telling the dropdown list frame (`DropDownList1`) to anchor relative to one of its own child list buttons (`DropDownList1Button1`). That creates a recursive anchor dependency, since buttons anchor to their parent lists.

Unfortunately at-present the addon compartment itself doesn't handle submenus too well - if the dropdown button is configured to open a submenu then the addon compartment would populate the submenu with a new copy of all registered buttons: https://github.com/Stanzilla/WoWUIBugs/issues/416

In the meantime you might want to change your OnClick handler to something like this. This will detect if the OnClick for your data object has been triggered from a dropdown list button and - if so - will instead open a new menu anchored to the addon compartment. It's a bit of a hack, but it's the best we can do for now.

```lua
OnClick = function(aClickedFrame, aButton)
    if aButton == "RightButton" then
        if AddonCompartmentFrame and aClickedFrame:GetParent() == DropDownList1 then
            -- You may want to anchor to "cursor" rather than AddonCompartmentFrame.
            ToggleDropDownMenu(1, nil, VuhDoMinimapDropDown, AddonCompartmentFrame, 0, 0);
        else
            ToggleDropDownMenu(1, nil, VuhDoMinimapDropDown, aClickedFrame:GetName(), 0, -5);
        end
    else
        VUHDO_slashCmd("opt");
    end
end
```

I'm not opposed to making changes to the library make detecting this a bit easier - but would rather wait and see if native submenu support can just be improved first.

**Comment by Ivaria** [comment]
Thanks so much for the workaround.  I'll give that a try.

**Comment by Ivaria** [comment]
Works well, I'll follow the issue tracking the upstream bug.

Thanks again!
